"use strict";

const http = require("http");
const fs = require("fs");
const path = require("path");

function normalizeRoutes(routes) {
  const out = {};
  for (const [p, def] of Object.entries(routes || {})) {
    if (typeof def === "function") {
      out[p] = { methods: ["GET"], run: def };
    } else {
      const methods = Array.isArray(def.method)
        ? def.method
        : [def.method || "GET"];
      out[p] = { methods, run: def.handler };
    }
  }
  return out;
}

function routeHandlerSource(routes) {
  const entries = Object.entries(routes || []).map(([p, def]) => {
    let methods;
    let run;
    if (typeof def === "function") {
      methods = ["GET"];
      run = def;
    } else {
      methods = Array.isArray(def.method) ? def.method : [def.method || "GET"];
      run = def.handler;
    }
    return (
      JSON.stringify(p) +
      ": { methods: " +
      JSON.stringify(methods) +
      ", run: " +
      run.toString() +
      " },"
    );
  });
  if (entries.length === 0) return "{}";
  return "{\n  " + entries.join("\n  ") + "\n}";
}

function respond(statusCode, data, extraHeaders) {
  const headers = {
    "content-type": "application/json",
    "access-control-allow-origin": "*",
  };
  Object.assign(headers, extraHeaders || {});
  return { statusCode, headers, body: JSON.stringify(data) };
}

function makeCtx(event, pathname, method, query) {
  const now = new Date();
  let body;
  try {
    body = JSON.parse(event.body || "null");
  } catch (err) {
    body = event.body || null;
  }
  return {
    path: pathname,
    method,
    query,
    headers: event.headers || {},
    event,
    body,
    now,
    iso: now.toISOString(),
    unix: Math.floor(now.getTime() / 1000),
    utc: now.toUTCString(),
    date: now.toISOString().slice(0, 10),
    time: now.toTimeString().slice(0, 8),
  };
}

function createHandler(routes) {
  const normalized = normalizeRoutes(routes);
  return async function handler(event) {
    const pathname = String(event.path || "/").replace(/\/+$/, "") || "/";
    const method = String(event.httpMethod || event.method || "GET").toUpperCase();
    const query = event.queryStringParameters || {};
    const route = normalized[pathname];
    if (!route) {
      return respond(404, {
        error: "No route for " + method + " " + pathname,
        routes: Object.keys(normalized),
      });
    }
    if (route.methods.indexOf(method) === -1) {
      return respond(405, { error: "Method not allowed" }, {
        allow: route.methods.join(", "),
      });
    }
    try {
      const data = await route.run(makeCtx(event, pathname, method, query));
      return respond(200, data);
    } catch (err) {
      return respond(500, {
        error: err && err.message ? err.message : String(err),
      });
    }
  };
}

class HqServer {
  constructor(config) {
    config = config || {};
    this.name = config.name || "hq-api";
    this.routes = config.routes || {};
  }

  handler(event) {
    return createHandler(this.routes)(event);
  }

  createHandler() {
    return createHandler(this.routes);
  }

  listen(port, callback) {
    const app = this.createHandler();
    const server = http.createServer((req, res) => {
      const url = new URL(req.url, "http://localhost");
      const method = req.method.toUpperCase();
      const query = Object.fromEntries(url.searchParams);
      if (url.pathname === "/_hq/routes") {
        const list = {};
        for (const [p, def] of Object.entries(this.routes)) {
          list[p] = typeof def === "function" ? ["GET"] : def.method;
        }
        res.writeHead(200, { "content-type": "application/json" });
        res.end(JSON.stringify(list));
        return;
      }
      const bodyChunks = [];
      req.on("data", (c) => bodyChunks.push(c));
      req.on("end", () => {
        app({
          path: url.pathname,
          httpMethod: method,
          queryStringParameters: query,
          headers: req.headers,
          body: Buffer.concat(bodyChunks).toString("utf8"),
        }).then((r) => {
          res.writeHead(r.statusCode, r.headers);
          res.end(r.body);
        });
      });
    });
    server.listen(port, callback);
    return server;
  }

  exportNetlify(dir) {
    const out = path.resolve(dir);
    fs.mkdirSync(path.join(out, "netlify", "functions"), { recursive: true });
    fs.writeFileSync(
      path.join(out, "netlify.toml"),
      [
        "[build]",
        '  publish = "."',
        "",
        "[functions]",
        '  directory = "netlify/functions"',
        "",
        "[[redirects]]",
        '  from = "/*"',
        '  to = "/.netlify/functions/api"',
        "  status = 200",
        "",
      ].join("\n")
    );
    fs.writeFileSync(
      path.join(out, "netlify", "functions", "api.js"),
      this.standaloneSource()
    );
    return out;
  }

  standaloneSource() {
    const lines = [
      '"use strict";',
      "// Generated by HQ — edit your hqfile instead of this file.",
      "// https://github.com/LordSK-unethical/HQ",
      "function respond(statusCode, data, extra) {",
      '  return { statusCode, headers: Object.assign({ "content-type": "application/json", "access-control-allow-origin": "*" }, extra || {}), body: JSON.stringify(data) };',
      "}",
      "const ROUTES = " + routeHandlerSource(this.routes) + ";",
      "exports.handler = async function (event) {",
      '  const pathname = String(event.path || "/").replace(/\\/+$/, "") || "/";',
      '  const method = String(event.httpMethod || event.method || "GET").toUpperCase();',
      "  const query = event.queryStringParameters || {};",
      "  const route = ROUTES[pathname];",
      '  if (!route) return respond(404, { error: "No route for " + method + " " + pathname, routes: Object.keys(ROUTES) });',
      '  if (route.methods.indexOf(method) === -1) return respond(405, { error: "Method not allowed" }, { allow: route.methods.join(", ") });',
      "  var body;",
      '  try { body = JSON.parse(event.body || "null"); } catch (e) { body = event.body || null; }',
      "  var now = new Date();",
      "  var ctx = { path: pathname, method: method, query: query, headers: event.headers || {}, event: event, body: body, now: now, iso: now.toISOString(), unix: Math.floor(now.getTime() / 1000), utc: now.toUTCString(), date: now.toISOString().slice(0, 10), time: now.toTimeString().slice(0, 8) };",
      "  try {",
      "    var data = await route.run(ctx);",
      "    return respond(200, data);",
      "  } catch (err) {",
      "    return respond(500, { error: err && err.message ? err.message : String(err) });",
      "  }",
      "};",
    ];
    return lines.join("\n");
  }
}

function define(config) {
  return new HqServer(config);
}

module.exports = { HqServer, define, createHandler, normalizeRoutes };